// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      if (web.apiKey.isEmpty) {
        throw UnsupportedError(
          'Firebase Web API Key is empty. Make sure you run the app using:\n'
          'flutter run --dart-define-from-file=.env'
        );
      }
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        if (android.apiKey.isEmpty) {
          throw UnsupportedError(
            'Firebase Android API Key is empty. Make sure you run the app using:\n'
            'flutter run --dart-define-from-file=.env'
          );
        }
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY'),
    appId: '1:198038988856:web:3a04f50e6f462ff62d1ecd',
    messagingSenderId: '198038988856',
    projectId: 'gen-lang-client-0855676972',
    authDomain: 'gen-lang-client-0855676972.firebaseapp.com',
    storageBucket: 'gen-lang-client-0855676972.firebasestorage.app',
    measurementId: 'G-VY20R5GW6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_ANDROID_API_KEY'),
    appId: '1:198038988856:android:d53018c7867c13922d1ecd',
    messagingSenderId: '198038988856',
    projectId: 'gen-lang-client-0855676972',
    storageBucket: 'gen-lang-client-0855676972.firebasestorage.app',
  );
}
